### ISSUE TITLE
"Slider Header" option in CBOX Theme Options page does not work

### ISSUE THREAD

**Issue by r-a-y** [cuny-academic-commons/cbox-theme#113]
Received a report that the **Slider Header** option listed on the CBOX Theme Options page under "Options > Homepage > Slider Setup" does not work:
http://commonsinabox.org/groups/help-support/forum/topic/register-page/#post-1700

I've confirmed that this is the case.

A potential solution involves adding a code snippet to the end of `/engine/includes/feature-slider/template.php`:

```
<?php
// Slider header option
echo apply_filters( 'the_content', infinity_option_get( 'cbox_flex_slider_title' ) );
?>
```

@BoweFrankema - Let me know if you're okay with adding this code snippet there.

**Comment by AweVision7** [comment]
It appears that the option to include "Freeform Text" under the slider has been removed, because its control at “Appearance>>CBOX Theme Options>>Home Page>>Slider Header” is not available (probably removed due to the previous comments above).

If so, can someone also please remove the "Freeform Text" image and its description from the tutorial at http://commonsinabox.org/documentation/cbox-slider ? 

This would help to remove any confusion to newbies like myself.

Thank you.

**Comment by r-a-y** [comment]
@AweVision7 - Thanks for finding this discrepancy with our documentation.  I've just updated the image and documentation page.
