### ISSUE TITLE
Issue with forcing SSL

### ISSUE THREAD

**Issue by r-a-y** [cuny-academic-commons/cbox-theme#239]
Reported here:
http://commonsinabox.org/groups/help-support/forum/topic/cbox-theme-vs-ssl/

Problem appears to occur when forcing SSL and with our CSS assets.  Interestingly, the reporter states that Infinity works.

**Comment by boonebgorges** [comment]
I managed to track this down to the fact that Infinity enqueues its "external" assets using a URL based on `wp_upload_dir()`. `wp_upload_dir()` is not scheme-sensitive; see https://core.trac.wordpress.org/ticket/25449

I didn't make an Infinity patch for this because I know we are supposed to be migrating to the newer version of Infinity at some point, but ping @MrMaz anyway :-D
