### ISSUE TITLE
Dev Docs image links broken

### ISSUE THREAD

**Issue by rgilman** [cuny-academic-commons/cbox-theme#245]
I found and then fixed this issue and want to share the fix.

The image links in the Dev Docs under Appearance > CBOX Theme Options were broken in both my local dev site (with MAMP) and a production site. I traced the issue to the use of '-' in the image filenames. Apparently the Markdown parser doesn't like that kind of naming. Replacing the hyphens with underscores in both the images names and the associated doc files fixes the issue.

**Comment by christianwach** [comment]
Thanks for the report @rgilman - I can confirm that the CBOX docs do not display images correctly. PR #250 fixes this, although it also appears that the docs also need updating since many of the images refer to a redundant need for the BuddyPress Template Pack plugin.

It also seems that there's a missing YouTube video embedded on the "BuddyPress Support" page. @BoweFrankema @MrMaz - do you know if the video exists elsewhere?

**Comment by boonebgorges** [comment]
Looks good! Thanks for tracking this down.
