### ISSUE TITLE
"This site is having difficulties" with theme

### ISSUE THREAD

**Issue by lordmatt** [cuny-academic-commons/cbox-theme#265]
I decided to test this theme. Not only did installing it automatically select it (not great on a live site) but also reduced the site to "This site is having difficulties".

Site is a network with the blog in question running BuddyPress.

**Comment by boonebgorges** [comment]
Hi @lordmatt - It's not clear to me how "installing" a theme would "automatically select it". My interpretation is that you downloaded the theme and put it into your wp-content/themes directory, and that you then found it activated on your site. Is that correct? I'm unsure how that could happen.

Or maybe what you mean is that you installed Commons In A Box, and during the installation routine, you selected and activated the theme? In this case, the "automatic" part is intentional - the Commons In A Box installation process is meant to reduce the number of clicks required for a community site setup.

"This site is having difficulties" is not a string that appears in WordPress or in Commons In A Box plugins/themes. I'm guessing it's a generic 500 notice from your host. Consider checking your PHP error logs to see if there are any fatal errors related to the theme.

I recommend having a staging or test site for evaluating plugins and themes before launching them on your main site.

**Comment by lordmatt** [comment]
I know, right. However, when using the CBox admin page, there is a prompt to use the theme. clicking it both fetches and applies the theme. That was when I learned that the theme did not work (at least with my configuration).

**Comment by r-a-y** [comment]
> I know, right. However, when using the CBox admin page, there is a prompt to use the theme. clicking it both fetches and applies the theme

That's correct.

Here's a screenshot of what is being referring to:

![2020-07-22_001122](https://user-images.githubusercontent.com/505921/88145885-a76dd400-cbea-11ea-95bd-29ff3c8ecc4b.png)

Good point, @lordmatt. Thanks for the UX feedback. We can probably make the messaging a little clearer or perhaps add a dialog prompt to ensure that when you click on the link, it will ask for confirmation before installing or activating the CBOX theme. I think the dialog prompt is the simplest thing to add. I'll make sure this is done before the next CBOX release.

> I decided to test this theme. Not only did installing it automatically select it (not great on a live site) but also reduced the site to "This site is having difficulties".

Sorry to hear about this. If possible, it would be great if you are able to duplicate the "site is having difficulties" bug on a fresh install and providing us with any PHP error log messages afterwards. That way, we can try to see what is causing the issue.

**Comment by r-a-y** [comment]
I've added the confirmation prompt.

Here's what it looks like:

![GIF of confirmation prompt](https://user-images.githubusercontent.com/505921/88242268-3840c000-cc7c-11ea-9066-631481521441.gif)

The text that appears in the prompt is:

> This will activate the Commons In A Box theme on your site.
>
> Are you sure you want to continue?

Let me know if that is clear enough.

**Comment by lordmatt** [comment]
Looks clear enough for me. Good change, thank you.
